spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zenkino
    username: postgres
    password: test@4321
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: configurations